import argparse
import subprocess
import os
import shutil
import sys


def download_site(url, dest_dir, user_agent=None, depth=None, exclude=None):
    """Download site using wget."""
    cmd = [
        "wget",
        "--mirror",             # recursive download
        "--convert-links",      # convert links for offline use
        "--page-requisites",    # download all assets
        "--adjust-extension",
        "--no-parent",
    ]
    if depth:
        cmd += ["--level", str(depth)]
    if user_agent:
        cmd += ["--user-agent", user_agent]
    if exclude:
        cmd += ["--exclude-domains", ",".join(exclude)]
    cmd += ["-P", dest_dir, url]

    print("Running:", " ".join(cmd))
    subprocess.run(cmd, check=True)


def create_wp_theme(theme_name, source_dir, output_dir, url):
    """Create WordPress theme from downloaded site."""
    theme_dir = os.path.join(output_dir, theme_name)
    site_dir = os.path.join(theme_dir, "site")
    if os.path.exists(theme_dir):
        shutil.rmtree(theme_dir)
    shutil.copytree(source_dir, site_dir)

    # style.css
    style_css = f"""/*
Theme Name: {theme_name}
Description: Static site generated from {url}
Version: 1.0
*/
"""
    with open(os.path.join(theme_dir, "style.css"), "w") as fh:
        fh.write(style_css)

    # index.php
    index_php = f"""<?php
// Auto generated by Enriscador Web
readfile(__DIR__ . '/site/index.html');
?>
"""
    with open(os.path.join(theme_dir, "index.php"), "w") as fh:
        fh.write(index_php)

    # functions.php (placeholder)
    with open(os.path.join(theme_dir, "functions.php"), "w") as fh:
        fh.write("<?php\n// Theme functions placeholder\n")

    print(f"WordPress theme created at {theme_dir}")


def parse_args():
    parser = argparse.ArgumentParser(description="Enriscador Web - Convert websites into static WordPress themes")
    parser.add_argument("url", help="URL to download")
    parser.add_argument("output", help="Output directory")
    parser.add_argument("--theme-name", default=None, help="Name of the WordPress theme")
    parser.add_argument("--user-agent", default=None, help="Custom User-Agent")
    parser.add_argument("--depth", type=int, help="Maximum crawl depth")
    parser.add_argument("--exclude", nargs="*", help="Domains to exclude")
    return parser.parse_args()


def main():
    args = parse_args()
    theme_name = args.theme_name or args.url.split('//')[-1].split('/')[0]
    download_dir = os.path.join(args.output, "download")
    os.makedirs(download_dir, exist_ok=True)

    try:
        download_site(args.url, download_dir, args.user_agent, args.depth, args.exclude)
    except subprocess.CalledProcessError as e:
        print("Error during download", e)
        sys.exit(1)

    # The downloaded site will be under download_dir/<domain>
    domain = args.url.split('//')[-1].split('/')[0]
    site_source = os.path.join(download_dir, domain)
    if not os.path.isdir(site_source):
        site_source = download_dir

    create_wp_theme(theme_name, site_source, args.output, args.url)


if __name__ == "__main__":
    main()
