<?php
// Auto generated by Enriscador Web
$index = __DIR__ . '/static/index.html';
if (is_file($index)) {
    readfile($index);
} else {
    status_header(404);
    echo 'Static index not found';
}
?>
